version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports
